### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by AlexisJC** [oroinc/oauth2-server#1]
Hi !

It seem the new documentation link introduced by the last commit is broken, the oro documentation display "The page you are looking for does not exist" message.

Can you tell me if the previous documentation is out to date ? (the previous readme) Thanks !

**Comment by vsoroka** [comment]
Hi.
Thank you to report the issue.We will fix the link. The correct link is https://doc.oroinc.com/master/backend/bundles/platform/OAuth2ServerBundle/

**Comment by anyt** [comment]
Fixed in https://github.com/oroinc/oauth2-server/commit/e49b6e943410f7e892c3ed961619e56359855e86,
Thank you!
